# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

test_that("check_data works", {

   expect_true(
    object = check_primary_color_is_ok(string = c("Gray", "Cinnamon", "Black"))
  )
  
})
