# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

#' Check if your selection it is in squirrels' fur color vector
#'
#' This function aims to evaluate whether a string character corresponds or not to the squirrels' fur color vector
#' 
#' @param string You need to input as the parameter a string color
#' 
#' @return A boolean: TRUE if your string it is in fur color vector. FALSE otherwise
#' 
#' @export
#'
#' @examples
#' check_primary_color_is_ok("White")
check_primary_color_is_ok <- function(string) {
  all_colors_OK <- all(
    string %in% c("Gray", "Cinnamon", "Black", NA)
  )
  return(all_colors_OK)
}
