# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

#' Get a message with a fur color
#' 
#' You can get a message with the fur color of interest with `get_message_fur_color()`
#' 
#' @param primary_fur_color Character. The primary fur color of interest
#'
#' @return None. Used for side effect. Outputs a message in the console
#' 
#' @export
#' 
#' @importFrom glue glue
#' 
#' @examples
#' get_message_fur_color(primary_fur_color = "Cinnamon")
get_message_fur_color <- function(primary_fur_color) {
  message(glue("We will focus on {primary_fur_color} squirrels"))
}
